M48
; DRILL file {KiCad 6.99.0-unknown-1140fd0fb0~148~ubuntu20.04.1} date Fri 29 Jul 2022 07:56:28 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-29T19:56:28-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.99.0-unknown-1140fd0fb0~148~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X7.814Y-3.1417
X7.814Y-3.315
T0
M30
