MCU_CHIP	 	= stm32f10x
MCU_CORE     	= cortex-m3
MCU_FLOAT    	= softfp
CORTEX_VER   	= $(ENV_CORTEX_VER)
OPENOCD_TARGET 	= stm32f1x

CFLAGS_COMMON += -DHSE_VALUE=8000000
CFLAGS_COMMON += -DHSE_PLLMUL=9 					# 8000000 x 9 = 72000000
CFLAGS_COMMON += -DSERIAL_NO_BASE_ADDRESS=0x1FFFF7E0
CFLAGS_COMMON += -fshort-enums -fsigned-char -mlittle-endian 
CFLAGS_COMMON += -mthumb -mthumb-interwork -mcpu=$(MCU_CORE) -mfloat-abi=$(MCU_FLOAT)
CFLAGS_COMMON += -DSTM32F10X_HD=1
CFLAGS_COMMON += -DDEBUG_UART=1
CFLAGS_COMMON += -DRS485_UART_0=0
CFLAGS_COMMON += -DDEBUG_SPEED_DEF=CARIBOU_UART_BAUD_RATE_115200
CFLAGS_COMMON += -DRS485_SPEED_0_DEF=CARIBOU_UART_BAUD_RATE_115200
CFLAGS_COMMON += -DUSDELAY_FACTOR=6
CFLAGS_COMMON += -DFEATURE_DELAY=64
CFLAGS_COMMON += -DLOCAL_OPTIMIZATION=1

CFLAGS_COMMON += -DLED0_POLARITY=true
CFLAGS_COMMON += -DLED1_POLARITY=true
CFLAGS_COMMON += -DBTN0_POLARITY=true
CFLAGS_COMMON += -DBTN1_POLARITY=true

# CARIBOU
CFLAGS_COMMON += -DUSE_NATIVE_STDARG=1
CFLAGS_COMMON += -DCARIBOU_POSIX_STDIO=1
CFLAGS_COMMON += -DUSART_QUEUE_SZ=64

# MICROSD
CFLAGS_COMMON += -DSDIO_BUSWIDTH=SDIO_BusWide_4b
CFLAGS_COMMON += -DLOCAL_OPTIMIZATION=1
CFLAGS_COMMON += -DMICROSD_SDIO=1

# ENC28J60
CFLAGS_COMMON += -DPRODUCT_HOSTNAME=\"sonic\"
CFLAGS_COMMON += -DPRODUCT_DHCP_THREAD_STACK_SZ=1024
CFLAGS_COMMON += -DPRODUCT_DHCP_THREAD_PRIORITY=1
CFLAGS_COMMON += -DPRODUCT_ETHIF_THREAD_STK_SZ=1024
CFLAGS_COMMON += -DPRODUCT_ETHIF_THREAD_PRIO=1
CFLAGS_COMMON += -DPRODUCT_ETHIN_WD_COUNT=100
CFLAGS_COMMON += -DETH_IRQn=EXTI9_5_IRQn
CFLAGS_COMMON += -DETH_LINE=EXTI_Line8
CFLAGS_COMMON += -DENC28J60_DMA_IRQ=DMA1_Channel5_IRQn
CFLAGS_COMMON += -DENC28J60_DMA_CHANNEL_RX=DMA1_Channel4
CFLAGS_COMMON += -DENC28J60_DMA_CHANNEL_TX=DMA1_Channel5
CFLAGS_COMMON += -DENC28J60_DMA_RX_IFCR=\(DMA_IFCR_CGIF4\|DMA_IFCR_CTCIF4\|DMA_IFCR_CHTIF4\|DMA_IFCR_CTEIF4\)
CFLAGS_COMMON += -DENC28J60_DMA_TX_IFCR=\(DMA_IFCR_CGIF5\|DMA_IFCR_CTCIF5\|DMA_IFCR_CHTIF5\|DMA_IFCR_CTEIF5\)
CFLAGS_COMMON += -DENC28J60_DMA_RX_TC=DMA_ISR_TCIF4
CFLAGS_COMMON += -DENC28J60_DMA_TX_TC=DMA_ISR_TCIF5
#CFLAGS_COMMON += -DENC28J60_USE_DMA=1
CFLAGS_COMMON += -DENC28J60_DMA=DMA1
CFLAGS_COMMON += -DENC28J60_SPI=SPI2
CFLAGS_COMMON += -DLWIP_TCP_CLOSE_TIMEOUT_MS_DEFAULT=5000
CFLAGS_COMMON += -DIP_FRAG_USES_STATIC_BUF=0			# static fragmentation buffer
CFLAGS_COMMON += -DIP_FRAG_MAX_MTU=1514
CFLAGS_COMMON += -DENC28J60_MAXFRAME=IP_FRAG_MAX_MTU
# CFLAGS_COMMON += -DENC28J60_PRESCALER=SPI_CR1_BR_0		# (72/4) = 18MHz
CFLAGS_COMMON += -DENC28J60_PRESCALER=SPI_CR1_BR_1		# (72/8) = 9MHz

# Serial SRAM 120 MHz Bus SPI0
CFLAGS_COMMON += -DSRAM_PRESCALER=SPI_CR1_BR_0		# (72/4) = 18MHz
CFLAGS_COMMON += -DSRAM_SPI=SPI1
CFLAGS_COMMON += -DSRAM_DMA=DMA1
CFLAGS_COMMON += -DSRAM_DMA_IRQ=DMA1_Channel3_IRQn
CFLAGS_COMMON += -DSRAM_DMA_CHANNEL_RX=DMA1_Channel2
CFLAGS_COMMON += -DSRAM_DMA_CHANNEL_TX=DMA1_Channel3
CFLAGS_COMMON += -DSRAM_DMA_RX_IFCR=\(DMA_IFCR_CGIF2\|DMA_IFCR_CTCIF2\|DMA_IFCR_CHTIF2\|DMA_IFCR_CTEIF2\)
CFLAGS_COMMON += -DSRAM_DMA_TX_IFCR=\(DMA_IFCR_CGIF3\|DMA_IFCR_CTCIF3\|DMA_IFCR_CHTIF3\|DMA_IFCR_CTEIF3\)
CFLAGS_COMMON += -DSRAM_DMA_RX_TC=DMA_ISR_TCIF2
CFLAGS_COMMON += -DSRAM_DMA_TX_TC=DMA_ISR_TCIF3
CFLAGS_COMMON += -DPATTERN_BUFFER_SZ=32
CFLAGS_COMMON += -DRAM_SIZE_BYTES=32768

# ADC DMA 
CFLAGS_COMMON += -DHW_ADC=ADC1						# ADC Controller 
CFLAGS_COMMON += -DHW_ADC_DMA=DMA1					# ADC DMA Controller 
CFLAGS_COMMON += -DHW_ADC_DMA_CH=DMA1_Channel1		# ADC DMA Channel 
CFLAGS_COMMON += -DHW_ADC_DMA_CNT=16				# ADC DMA Channel Count
CFLAGS_COMMON += -DHW_ADC_TIM=TIM2					# ADC Timer
CFLAGS_COMMON += -DHW_ADC_TIM_CH=2					# ADC Timer Channel
CFLAGS_COMMON += -DXDUC_ADC_TIM_BASE_HZ=72000000
# EXTSEL Bits: Timer 2 CC2
CFLAGS_COMMON += -DHW_ADC_INJECT_MASK=\(ADC_CR2_JEXTSEL_1\|ADC_CR2_JEXTSEL_0\)
CFLAGS_COMMON += -DHW_XDUC_DMA_ADC_CHAN=8			# XDUC ADC CHAN
CFLAGS_COMMON += -DXDUC_DMA_IRQ=DMA1_Channel1_IRQn
# ADC Sample buffer must be even multiples of 1024
# Samples are 16-bit words. This size will be divided
# into two buffers for operation in double buffer 
# streaming mode
CFLAGS_COMMON += -DXDUC_ADC_SAMPLE_SZ=2048  		   	# 1K * 2

# Enable timer outputs on LED 
# outputs instead of GPIO 
CFLAGS_COMMON += -DTIM4_BUS_HZ=72000000
CFLAGS_COMMON += -DHW_DAC_PWM_BUS_HZ=TIM4_BUS_HZ
CFLAGS_COMMON += -DHW_DAC_PWM_TIM=TIM4
CFLAGS_COMMON += -DHW_DAC_PWM_CH0=PWM_CHANNEL_3
CFLAGS_COMMON += -DHW_DAC_PWM_CH1=PWM_CHANNEL_4
CFLAGS_COMMON += -DHW_DAC_PWM_HZ=300000

CFLAGS_COMMON += -DPRODUCT_PROTOCOL_SNMP_ENABLED=1
CFLAGS_COMMON += -DPRODUCT_IF_NAME=\"ei\"
CFLAGS_COMMON += -DPRODUCT_HTTP_SERVER_STK_SZ=1024
CFLAGS_COMMON += -DPRODUCT_HTTP_THREAD_STK_SZ=\(1024*4\)
CFLAGS_COMMON += -DPRODUCT_FTP_SERVER_STK_SZ=1024
CFLAGS_COMMON += -DPRODUCT_FTP_THREAD_STK_SZ=\(1024*4\)
CFLAGS_COMMON += -DPRODUCT_HTTP_SERVER_NAME=\"httpd\"
CFLAGS_COMMON += -DPRODUCT_HTTP_THREAD_PRIO=1
CFLAGS_COMMON += -DPRODUCT_HTTPD_WD_COUNT=100
CFLAGS_COMMON += -DPRODUCT_HTTP_SEND_BUFFER_SZ=1024
CFLAGS_COMMON += -DPRODUCT_HTTP_PORT=80
CFLAGS_COMMON += -DPRODUCT_HTTP_BACKLOG=16
CFLAGS_COMMON += -DPRODUCT_HTTP_SESSION_NAME=\"http\" 
CFLAGS_COMMON += -DPRODUCT_HTTP_SESSION_PRIO=1
CFLAGS_COMMON += -DPRODUCT_HTTP_WD_COUNT=100
CFLAGS_COMMON += -DPRODUCT_I2CSPEED=30
CFLAGS_COMMON += -DPRODUCT_HTTP_ROOT=\"/\"
CFLAGS_COMMON += -DPRODUCT_EEPROM_BPP=16
CFLAGS_COMMON += -DPRODUCT_VERSION=\"0.1\"

CFLAGS_COMMON += -DPRODUCT_DEBUG_SETTINGS=1
CFLAGS_COMMON += -DPRODUCT_THREAD_NORMAL_PRIO=1

# sources
include ${SRC_ROOT}/_bsp/${TARGET}/_src.mk
