MCU_CHIP	 	= gd32vf103
MCU_MARCH    	= rv32imac
MCU_MABI    	= ilp32
OPENOCD_TARGET 	= ${ENV_OPENOCD_TARGET}

CFLAGS_COMMON += -Wno-address-of-packed-member
CFLAGS_COMMON += -DCARIBOU_FLOAT=1
CFLAGS_COMMON += -DUSE_NATIVE_STDARG=1
CFLAGS_COMMON += -DSERIAL_NO_BASE_ADDRESS=0x1FFFF7E8
CFLAGS_COMMON += -fshort-enums -fsigned-char -march=$(MCU_MARCH) -mabi=$(MCU_MABI)

CFLAGS_COMMON += -DUSART_QUEUE_SZ=64

CFLAGS_COMMON += -DDEBUG_UART=2 -DDEBUG_SPEED_DEF=CARIBOU_UART_BAUD_RATE_115200
CFLAGS_COMMON += -DRS485_UART=1 -DRS485_SPEED_DEF=CARIBOU_UART_BAUD_RATE_115200

CFLAGS_COMMON += -DUSDELAY_FACTOR=11
CFLAGS_COMMON += -DHXTAL_VALUE=8000000
CFLAGS_COMMON += -DHSE_VALUE=HXTAL_VALUE 
CFLAGS_COMMON += -DMCP6S92_SPI_PRESCALER=SPI_PSC_64	# (48/64) = 0.75MHz

CFLAGS_COMMON += -DMCP6S92_SPI=SPI1
CFLAGS_COMMON += -DSPI_DATASIZE_8BIT=PI_FRAMESIZE_8BIT

CFLAGS_COMMON += -DLED0_POLARITY=false
CFLAGS_COMMON += -DLED1_POLARITY=false
CFLAGS_COMMON += -DLED2_POLARITY=false
CFLAGS_COMMON += -DFEATURE_DELAY=64

CFLAGS_COMMON += -DENABLE_BCAST_REPLY=FALSE
CFLAGS_COMMON += -DDISCO_REFRESH_PERIOD=15*1000*60
CFLAGS_COMMON += -DMIN_DISCO_DELAY=64				# Minimum discovery delay
CFLAGS_COMMON += -DMAX_DISCO_DELAY=250				# Maximum discovery delay

CFLAGS_COMMON += -DTIM_OUT_IRQ=TIMER0_UP_IRQn
CFLAGS_COMMON += -DTIM1_BUS_HZ=108000000			# Timer Reference Frequency
CFLAGS_COMMON += -DTIM2_BUS_HZ=54000000				# Timer Reference Frequency
CFLAGS_COMMON += -DTIM_TRIGGER=TIMER1				# Edge-trigger timer (CH1 Only)
CFLAGS_COMMON += -DTIM_OUT=TIMER0					# Waveform output timer
CFLAGS_COMMON += -DTIM_OUT_CHAN=TX_GEN_CHANNEL_1	# Wafeform output channel (TXP)
CFLAGS_COMMON += -DTIM_OUT_BUS_HZ=TIM1_BUS_HZ		# Output waveform timer reference frquency
CFLAGS_COMMON += -DHW_TIM_TX_FREQ=6000000			# TX Timer Frequency
CFLAGS_COMMON += -DHW_TIM_RX_FREQ=6000000			# RX Timer Frequency

CFLAGS_COMMON += -DHW_ADC_DMA=DMA0					# ADC DMA Controller 
CFLAGS_COMMON += -DHW_ADC_DMA_CH=DMA_CH0			# ADC DMA Channel 
CFLAGS_COMMON += -DHW_ADC_DMA_CNT=18				# ADC DMA Channel Count

CFLAGS_COMMON += -DVREF_ADC=ADC0
CFLAGS_COMMON += -DVREF_ADC_CH=15					# -2 for regular sequnce
CFLAGS_COMMON += -DVREF_ADC_CH_TEMPC=14				# -2hw_adc
CFLAGS_COMMON += -DVREF_V=2.4f

CFLAGS_COMMON += -DTIM_IN=TIM2						# Waveform output timer
CFLAGS_COMMON += -DTIM_IN_CHAN=RX_GEN_CHANNEL_4		# Waveform output channel
CFLAGS_COMMON += -DTIM_IN_BUS_HZ=TIM2_BUS_HZ		# Output waveform timer reference frquency 

CFLAGS_COMMON += -DXF_USE_FP=1
CFLAGS_COMMON += -DXF_USE_LLI=1

CFLAGS_COMMON += -DPIEZO_MAX_DAC_PWR=0x0AFF
CFLAGS_COMMON += -DPIEZO_TX_XDUC_POWER=90.0f
CFLAGS_COMMON += -DPIEZO_TX_XDUC_HZ=50000			# Transducer frequency
CFLAGS_COMMON += -DPIEZO_TX_XDUC_CYCLES=16			# Number of cycles in a chirp
CFLAGS_COMMON += -DXDUC_ARM_DELAY_MS=10
CFLAGS_COMMON += -DXDUC_TIMEOUT_MS=50
CFLAGS_COMMON += -DXDUC_HEARTBEAT_MS=50
CFLAGS_COMMON += -DMODBUS_SLAVE_ID=0				# Default Slave ID

CFLAGS_COMMON += -DPRODUCT_VERSON_WORD=0x0101
CFLAGS_COMMON += -DPRODUCT_HEARTBEAT_PERIOD=100
CFLAGS_COMMON += -DMODBUS_THREAD_STK_SZ=2048

# sources
include ${SRC_ROOT}/_bsp/${TARGET}/_src.mk
