MCU_CHIP	 	= stm32f10x
MCU_CORE     	= cortex-m3
MCU_FLOAT    	= softfp
CORTEX_VER   	= $(ENV_CORTEX_VER)
OPENOCD_TARGET 	= stm32f1x

# CFLAGS_COMMON += -DSEMIHOST_STDERR=1					# Output to semihost when debugging
CFLAGS_COMMON += -Wno-address-of-packed-member
CFLAGS_COMMON += -DNO_SYSTEM_INIT=1						# Don't call the SystemInit() fn.
CFLAGS_COMMON += -DHXTAL_VALUE=8000000				
CFLAGS_COMMON += -DHSE_PLLMUL=11						# 11 * 6.25Mhz = 68.75MHz PLL
CFLAGS_COMMON += -DHSI_PLLMUL=16						# 16 * 4Mhz = 64MHz PLL
CFLAGS_COMMON += -fshort-enums -fsigned-char -mlittle-endian 
CFLAGS_COMMON += -DSERIAL_NO_BASE_ADDRESS=0x1FFFF7E0
CFLAGS_COMMON += -mthumb -mthumb-interwork -mcpu=$(MCU_CORE) -mfloat-abi=$(MCU_FLOAT)
CFLAGS_COMMON += -DUSART_QUEUE_SZ=64 -DSTM32F10X_MD=1
CFLAGS_COMMON += -DDEBUG_UART=0
CFLAGS_COMMON += -DRS485_UART_0=1
CFLAGS_COMMON += -DDEBUG_SPEED_DEF=CARIBOU_UART_BAUD_RATE_115200
CFLAGS_COMMON += -DRS485_SPEED_0_DEF=CARIBOU_UART_BAUD_RATE_115200
CFLAGS_COMMON += -DETH_IRQn=EXTI9_5_IRQn
CFLAGS_COMMON += -DETH_LINE=EXTI_Line8
CFLAGS_COMMON += -DLED0_POLARITY=true
CFLAGS_COMMON += -DLED1_POLARITY=true
CFLAGS_COMMON += -DUSDELAY_FACTOR=6
CFLAGS_COMMON += -DFEATURE_DELAY=64

CFLAGS_COMMON += -DMODBUS_THREAD_STK_SZ=2048
CFLAGS_COMMON += -DMIN_DISCO_DELAY=10					# Minimum discovery delay
CFLAGS_COMMON += -DMAX_DISCO_DELAY=64					# Maximum discovery delay

CFLAGS_COMMON += -DPIEZO_MAX_DAC_PWR=0x0AFF
CFLAGS_COMMON += -DPIEZO_TX_XDUC_POWER=90.0f
CFLAGS_COMMON += -DPIEZO_TX_XDUC_HZ=50000				# Transducer frequency
CFLAGS_COMMON += -DPIEZO_TX_XDUC_CYCLES=16				# Number of cycles in a chirp
CFLAGS_COMMON += -DXDUC_ARM_DELAY_MS=10
CFLAGS_COMMON += -DXDUC_TIMEOUT_MS=50
CFLAGS_COMMON += -DXDUC_HEARTBEAT_MS=50
CFLAGS_COMMON += -DMODBUS_SLAVE_ID=0					# Default Slave ID

# Enable timer outputs on LED 
# outputs instead of GPIO 
CFLAGS_COMMON += -DTIM4_BUS_HZ=72000000
CFLAGS_COMMON += -DHW_DAC_PWM_BUS_HZ=TIM4_BUS_HZ
CFLAGS_COMMON += -DHW_DAC_PWM_TIM=TIM4
CFLAGS_COMMON += -DHW_DAC_PWM_CH0=PWM_CHANNEL_3
CFLAGS_COMMON += -DHW_DAC_PWM_CH1=PWM_CHANNEL_4
CFLAGS_COMMON += -DHW_DAC_PWM_HZ=300000

CFLAGS_COMMON += -DV_PGA_OFFSET=DAC_CHANNEL_1
CFLAGS_COMMON += -DDAC_V_CAP_CTL=DAC_CHANNEL_2
CFLAGS_COMMON += -DHW_ADC_DMA_CNT=16					# ADC DMA Channel Count

CFLAGS_COMMON += -DPRODUCT_DEBUG_SETTINGS=1
CFLAGS_COMMON += -DPRODUCT_THREAD_NORMAL_PRIO=1

# sources
include ${SRC_ROOT}/_bsp/${TARGET}/_src.mk
