MCU_CHIP	 	= stm32f7xx
MCU_CORE     	= cortex-m7
MCU_FLOAT    	= soft
CORTEX_VER   	= $(ENV_CORTEX_VER)
OPENOCD_TARGET 	= stm32f7x

CFLAGS_COMMON += -D__BARE_METAL__=1
CFLAGS_COMMON += -fshort-enums -fsigned-char -mlittle-endian -mthumb -mthumb-interwork -mcpu=$(MCU_CORE) -mfloat-abi=$(MCU_FLOAT)
CFLAGS_COMMON += -DHSE_VALUE=8000000U 
CFLAGS_COMMON += -DCARIBOU_FLOAT=1 -DSTM32F746xx=1 
CFLAGS_COMMON += -DSERIAL_NO_BASE_ADDRESS=0x1FFFF7E8

CFLAGS_COMMON += -DLED0_POLARITY=true
CFLAGS_COMMON += -DBLINK_RATE_LO=125
CFLAGS_COMMON += -DBLINK_RATE_HI=64

CFLAGS_COMMON += -DBOOT_LOADER=\"LOADER.S19\"
CFLAGS_COMMON += -DBOOT_FIRMWARE=\"FIRMWARE.S19\"
CFLAGS_COMMON += -DBOOT_ARMED_TIMEOUT=4000

CFLAGS_COMMON += -DBOOT_LOAD_ADDR_BASE=0x20000000
CFLAGS_COMMON += -DBOOT_LOAD_ADDR_TOP=0x2000FFFF

CFLAGS_COMMON += -DBOOSTRAP_DEBUG=0

# sources
include ${SRC_ROOT}/_bsp/${TARGET}/_src.mk

