MCU_CHIP	 	= gd32vf103
MCU_MARCH    	= rv32imac
MCU_MABI    	= ilp32
OPENOCD_TARGET 	= ${ENV_OPENOCD_TARGET}

CFLAGS_COMMON += -DUSDELAY_FACTOR=11
CFLAGS_COMMON += -DHXTAL_VALUE=8000000
CFLAGS_COMMON += -DDEBUG_UART=2 -DRS485_UART_0=0 
CFLAGS_COMMON += -DUSART_QUEUE_SZ=64 -DHSE_VALUE=8000000U -DCARIBOU_FLOAT=1
CFLAGS_COMMON += -DSERIAL_NO_BASE_ADDRESS=0x1FFFF7E8
CFLAGS_COMMON += -fshort-enums -fsigned-char -march=$(MCU_MARCH) -mabi=$(MCU_MABI)

CFLAGS_COMMON += -DSRAM_RD_HACK=1
CFLAGS_COMMON += -DRAM_SIZE_BYTES=\(256\*1024\)
CFLAGS_COMMON += -DPATTERN_BUFFER_SZ=32

CFLAGS_COMMON += -DSRAM_SPI=SPI0
CFLAGS_COMMON += -DSRAM_PRESCALER=SPI_PSC_4		    # (108/4) = 27MHz
CFLAGS_COMMON += -DSRAM_DMA=DMA0
CFLAGS_COMMON += -DSRAM_DMA_CHANNEL_RX=DMA_CH1
CFLAGS_COMMON += -DSRAM_DMA_CHANNEL_TX=DMA_CH2
CFLAGS_COMMON += -DMICROSD_SPI=SPI1
CFLAGS_COMMON += -DMICROSD_PRESCALER=SPI_PSC_8		# (54/8) = 6.75MHz
CFLAGS_COMMON += -DNULL_TF_CD=1						# No TF card-detect pin
CFLAGS_COMMON += -DBTN0_POLARITY=true
CFLAGS_COMMON += -DLED0_POLARITY=true
CFLAGS_COMMON += -DLED1_POLARITY=true
CFLAGS_COMMON += -DLED2_POLARITY=true
CFLAGS_COMMON += -DFEATURE_DELAY=64

CFLAGS_COMMON += -DFEATURE_MODBUS_MASTER_PORT_0=RS485_UART_0
CFLAGS_COMMON += -DFEATURE_MODBUS_MASTER_DIR_0=gpio_rs485_dir 
CFLAGS_COMMON += -DFEATURE_MODBUS_MASTER_BAUD_0=115200

CFLAGS_COMMON += -DDISCO_REFRESH_PERIOD=15*1000*60
CFLAGS_COMMON += -DMIN_DISCO_DELAY=10				# Minimum discovery delay
CFLAGS_COMMON += -DMAX_DISCO_DELAY=64				# Maximum discovery delay

CFLAGS_COMMON += -DTIM_OUT_IRQ=TIMER0_UP_IRQn
CFLAGS_COMMON += -DTIM1_BUS_HZ=108000000			# Timer Reference Frequency
CFLAGS_COMMON += -DTIM2_BUS_HZ=48000000				# Timer Reference Frequency
CFLAGS_COMMON += -DTIM_TRIGGER=TIMER1				# Edge-trigger timer (CH1 Only)
CFLAGS_COMMON += -DTIM_OUT=TIMER0					# Waveform output timer
CFLAGS_COMMON += -DTIM_OUT_CHAN=TX_GEN_CHANNEL_1	# Wafeform output channel (TXP)
CFLAGS_COMMON += -DTIM_OUT_BUS_HZ=TIM1_BUS_HZ		# Output waveform timer reference frquency
CFLAGS_COMMON += -DHW_TIM_TX_FREQ=6000000			# TX Timer Frequency
CFLAGS_COMMON += -DHW_TIM_RX_FREQ=6000000			# RX Timer Frequency

CFLAGS_COMMON += -DTIM_IN=TIM2						# Waveform output timer
CFLAGS_COMMON += -DTIM_IN_CHAN=RX_GEN_CHANNEL_4		# Waveform output channel
CFLAGS_COMMON += -DTIM_IN_BUS_HZ=TIM2_BUS_HZ		# Output waveform timer reference frquency 

CFLAGS_COMMON += -DPIEZO_MAX_DAC_PWR=0x0AFF
CFLAGS_COMMON += -DPIEZO_TX_XDUC_POWER=90.0f
CFLAGS_COMMON += -DPIEZO_TX_XDUC_HZ=50000			# Transducer frequency
CFLAGS_COMMON += -DPIEZO_TX_XDUC_CYCLES=10			# Number of cycles in a chirp
CFLAGS_COMMON += -DXDUC_BAUD_RATE=115200
CFLAGS_COMMON += -DXDUC_ARM_DELAY_MS=10
CFLAGS_COMMON += -DXDUC_TIMEOUT_MS=50
CFLAGS_COMMON += -DXDUC_HEARTBEAT_MS=50
CFLAGS_COMMON += -DMODBUS_SLAVE_ID=0				# Default Slave ID

CFLAGS_COMMON += -DMCP6S92_SPI=SPI2
CFLAGS_COMMON += -DMCP6S92_SPI_PRESCALER=\(SPI_CR1_BR_2\|SPI_CR1_BR_2\)		# (48/64) = 0.75MHz
CFLAGS_COMMON += -DSPI_DATASIZE_8BIT=\(SPI_CR2_DS_2\|SPI_CR2_DS_1\|SPI_CR2_DS_0\)

CFLAGS_COMMON += -DPRODUCT_VERSON_WORD=0x0101
CFLAGS_COMMON += -DPRODUCT_HEARTBEAT_PERIOD=100
CFLAGS_COMMON += -DMODBUS_THREAD_STK_SZ=2048

# sources
include ${SRC_ROOT}/_bsp/${TARGET}/_src.mk

include ${SRC_ROOT}/filesystem/_src.mk
